### ISSUE TITLE
iPhone install

### ISSUE THREAD

**Issue by friass1441** [lumo93/RE-FLEX#3] opened 2023-04-22 19:19 UTC
I'm a bit loss on how to install it on iphone

**Comment by lumo93** [comment] 2023-04-22 20:34
My apologies, the program was intended to work with python, and it uses GUI elements so you'll need to be running it on a desktop computer like Windows or Linux. I haven't tested and I don't think it would work with Android and iPhone but it will work for users who use either Android or iPhone. When you set up your user agent it will show us an Android device but that's fine, it's what Amazon will see the second device as.

**Comment by friass1441** [comment] 2023-04-23 00:05
Perfect, I understand, but how do I do the process of installation on windows?

**Comment by lumo93** [comment] 2023-04-23 00:40
You just need python for Windows, it supports 3.9 3.10 and 3.11

From there, you download the repo as is and run script dock. The readme should have instructions but they may not be clear, let me know.

**Comment by lumo93** [comment] 2023-04-25 04:43
I will be closing this issue, if you need help with setup, please visit r/RealAmazonFlexDrivers subreddit for general assistance. same username lumo93

**Closed as completed by lumo93** 2023-04-25 04:43 UTC
